// @generated by codegen/generate.mjs — do not edit.
//
// Regenerate with `npm run generate` in codegen/, after
// `npm run fetch-schema` if the API has moved on. Every field below is
// derived from schema/recording.graphql and schema/schema.graphql; what
// neither can express comes from schema/fields.mjs.
//
// A field is `non_null` when the schema marks every link above it
// `@semanticNonNull`. If that annotation is ever removed upstream, the
// change shows up here as a `String` becoming an `Option<String>`.

use crate::model::text;
use crate::{FieldDoc, Fields};
use serde::Deserialize;

/// The query this model deserializes, sent verbatim at runtime.
pub const QUERY: &str = include_str!("../../schema/recording.graphql");

/// Every path a template may reference.
pub static FIELDS: &[FieldDoc] = &[
    FieldDoc::non_null(
        "id",
        "FindOpera recording id — always present, good for disambiguating",
    ),
    FieldDoc::non_null("url", "Canonical findopera.com URL for the recording"),
    FieldDoc::new("year", "Year recorded. Often absent on older entries"),
    FieldDoc::new("month", "Month recorded, zero-padded (04). Usually absent"),
    FieldDoc::new("day", "Day recorded, zero-padded (09). Usually absent"),
    FieldDoc::new("orchestra", "Orchestra name"),
    FieldDoc::new("chorus", "Chorus name. Often absent"),
    FieldDoc::non_null("conductor.fullName", "Conductor, e.g. Charles Mackerras"),
    FieldDoc::non_null("conductor.firstName", "Conductor given name(s)"),
    FieldDoc::non_null("conductor.lastName", "Conductor surname"),
    FieldDoc::new("conductor.born", "Conductor year of birth"),
    FieldDoc::new("conductor.died", "Conductor year of death"),
    FieldDoc::non_null(
        "opera.title",
        "Title in the original language — the safest title field",
    ),
    FieldDoc::new(
        "opera.englishTitle",
        "English title. Absent unless the opera has one",
    ),
    FieldDoc::new("opera.librettist", "Librettist. Absent for most recordings"),
    FieldDoc::non_null("opera.url", "Canonical findopera.com URL for the opera"),
    FieldDoc::new("opera.language.name", "Language sung, e.g. German"),
    FieldDoc::new("opera.language.abbreviation", "Language code, e.g. de"),
    FieldDoc::non_null("composer.fullName", "Composer, e.g. George Frideric Handel"),
    FieldDoc::non_null("composer.firstName", "Composer given name(s)"),
    FieldDoc::non_null(
        "composer.lastName",
        "Composer surname — the usual top-level folder",
    ),
    FieldDoc::new("composer.born", "Composer year of birth"),
    FieldDoc::new("composer.died", "Composer year of death"),
    FieldDoc::new("opera.language", "Language sung, e.g. German"),
    FieldDoc::new("upc", "First barcode listed for the release. Often absent"),
    FieldDoc::new("singers", "All noted singers, full names, comma-joined"),
    FieldDoc::new(
        "singers.lastNames",
        "All noted singers, surnames only, comma-joined",
    ),
    FieldDoc::new("singer1", "First noted singer, full name"),
    FieldDoc::new("singer2", "Second noted singer, if any"),
    FieldDoc::new("singer3", "Third noted singer, if any"),
    FieldDoc::new("singer1.lastName", "First noted singer, surname only"),
    FieldDoc::new("singer2.lastName", "Second noted singer, surname only"),
    FieldDoc::new("singer3.lastName", "Third noted singer, surname only"),
];

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Recording {
    pub id: i64,
    pub url: String,
    #[serde(default, deserialize_with = "crate::model::de::num")]
    pub year: Option<i64>,
    #[serde(default, deserialize_with = "crate::model::de::num")]
    pub month: Option<i64>,
    #[serde(default, deserialize_with = "crate::model::de::num")]
    pub day: Option<i64>,
    #[serde(default, deserialize_with = "crate::model::de::text")]
    pub orchestra: Option<String>,
    #[serde(default, deserialize_with = "crate::model::de::text")]
    pub chorus: Option<String>,
    pub conductor: Conductor,
    pub noted_singers: Vec<Singer>,
    pub opera: Opera,
    pub upcs: Vec<Upc>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Conductor {
    pub full_name: String,
    pub first_name: String,
    pub last_name: String,
    #[serde(default, deserialize_with = "crate::model::de::num")]
    pub born: Option<i64>,
    #[serde(default, deserialize_with = "crate::model::de::num")]
    pub died: Option<i64>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Singer {
    pub full_name: String,
    pub first_name: String,
    pub last_name: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Opera {
    pub title: String,
    #[serde(default, deserialize_with = "crate::model::de::text")]
    pub english_title: Option<String>,
    #[serde(default, deserialize_with = "crate::model::de::text")]
    pub librettist: Option<String>,
    pub url: String,
    pub language: Option<Language>,
    pub composer: Composer,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Language {
    pub name: String,
    pub abbreviation: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Composer {
    pub full_name: String,
    pub first_name: String,
    pub last_name: String,
    #[serde(default, deserialize_with = "crate::model::de::num")]
    pub born: Option<i64>,
    #[serde(default, deserialize_with = "crate::model::de::num")]
    pub died: Option<i64>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Upc {
    pub upc: String,
}

impl Fields for Recording {
    fn required(&self, path: &str) -> String {
        match path {
            "id" => self.id.to_string(),
            "url" => self.url.clone(),
            "conductor.fullName" => self.conductor.full_name.clone(),
            "conductor.firstName" => self.conductor.first_name.clone(),
            "conductor.lastName" => self.conductor.last_name.clone(),
            "opera.title" => self.opera.title.clone(),
            "opera.url" => self.opera.url.clone(),
            "composer.fullName" => self.opera.composer.full_name.clone(),
            "composer.firstName" => self.opera.composer.first_name.clone(),
            "composer.lastName" => self.opera.composer.last_name.clone(),
            other => unreachable!("{other} is not a non-null field"),
        }
    }

    fn optional(&self, path: &str) -> Option<String> {
        match path {
            "year" => self.year.map(|v| v.to_string()),
            "month" => self.month.map(|v| format!("{v:02}")),
            "day" => self.day.map(|v| format!("{v:02}")),
            "orchestra" => self.orchestra.clone(),
            "chorus" => self.chorus.clone(),
            "conductor.born" => self.conductor.born.map(|v| v.to_string()),
            "conductor.died" => self.conductor.died.map(|v| v.to_string()),
            "opera.englishTitle" => self.opera.english_title.clone(),
            "opera.librettist" => self.opera.librettist.clone(),
            "opera.language.name" => Some(self.opera.language.as_ref()?.name.clone()),
            "opera.language.abbreviation" => {
                Some(self.opera.language.as_ref()?.abbreviation.clone())
            }
            "composer.born" => self.opera.composer.born.map(|v| v.to_string()),
            "composer.died" => self.opera.composer.died.map(|v| v.to_string()),
            "opera.language" => Some(self.opera.language.as_ref()?.name.clone()),
            "upc" => self.upcs.first().and_then(|e| text(&e.upc)),
            "singers" => {
                let vs: Vec<String> = self
                    .noted_singers
                    .iter()
                    .filter_map(|e| text(&e.full_name))
                    .collect();
                (!vs.is_empty()).then(|| vs.join(", "))
            }
            "singers.lastNames" => {
                let vs: Vec<String> = self
                    .noted_singers
                    .iter()
                    .filter_map(|e| text(&e.last_name))
                    .collect();
                (!vs.is_empty()).then(|| vs.join(", "))
            }
            "singer1" => self.noted_singers.first().and_then(|e| text(&e.full_name)),
            "singer2" => self.noted_singers.get(1).and_then(|e| text(&e.full_name)),
            "singer3" => self.noted_singers.get(2).and_then(|e| text(&e.full_name)),
            "singer1.lastName" => self.noted_singers.first().and_then(|e| text(&e.last_name)),
            "singer2.lastName" => self.noted_singers.get(1).and_then(|e| text(&e.last_name)),
            "singer3.lastName" => self.noted_singers.get(2).and_then(|e| text(&e.last_name)),
            other => unreachable!("{other} is not a nullable field"),
        }
    }
}
