// Emits the table of types the CRUD commands work through.
//
// Twenty types, each with the same four operations and a pair of input
// objects. Written by hand that is eighty things to keep in step with a schema
// that moves; derived from the schema it is one thing that cannot drift, and
// CI fails when it does.

import { getNamedType, isNonNullType, isListType } from "graphql";

/** `RecordingURL` -> `recording-url`, `SpotifyAlbum` -> `spotify-album`. */
export function kebab(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1-$2")
    .toLowerCase();
}

/** What a field looks like once it is JSON rather than GraphQL. */
function jsonType(type) {
  if (isListType(type)) return "array";
  if (isNonNullType(type) || isListType(type)) return jsonType(getNamedType(type));
  switch (getNamedType(type).name) {
    case "Int":
      return "integer";
    case "Float":
      return "number";
    case "Boolean":
      return "boolean";
    default:
      return "string";
  }
}

function rustStr(s) {
  return JSON.stringify(s ?? "");
}

function fields(inputType) {
  if (!inputType) return [];
  return Object.values(inputType.getFields())
    .map((f) => ({
      name: f.name,
      json: jsonType(f.type),
      required: isNonNullType(f.type),
      about: f.description ?? null,
    }))
    .sort((a, b) => {
      // Required first, so the shape of the thing is visible before its
      // options; then alphabetical, so the order never depends on the schema's.
      if (a.required !== b.required) return a.required ? -1 : 1;
      return a.name.localeCompare(b.name);
    });
}

export function crud(schema, getOperations) {
  const mutations = schema.getMutationType().getFields();
  const queries = schema.getQueryType().getFields();

  const types = [];
  for (const [name, field] of Object.entries(mutations)) {
    const m = /^add([A-Z][A-Za-z]*)$/.exec(name);
    if (!m) continue;
    const graphql = m[1];
    // Only types with the whole set; anything partial is a special case and
    // does not belong in a uniform command.
    if (!mutations[`update${graphql}`] || !mutations[`delete${graphql}`]) continue;
    const root = `get${graphql}ById`;
    if (!queries[root]) continue;

    const operation = getOperations.get(graphql);
    if (!operation) {
      throw new Error(
        `schema/get.graphql has no query for ${graphql}; every type with CRUD needs one`,
      );
    }

    const inputArg = field.args.find((a) => a.name === "input");
    const updateArg = mutations[`update${graphql}`].args.find((a) => a.name === "input");

    types.push({
      name: kebab(graphql),
      graphql,
      get: operation,
      root,
      add: name,
      update: `update${graphql}`,
      remove: `delete${graphql}`,
      // The input object names, taken from the schema rather than assembled
      // from the type name, so a server that ever spells one differently is
      // followed instead of guessed at.
      createInput: getNamedType(inputArg.type).name,
      editInput: getNamedType(updateArg.type).name,
      create: fields(inputArg && getNamedType(inputArg.type)),
      edit: fields(updateArg && getNamedType(updateArg.type)),
    });
  }
  types.sort((a, b) => a.name.localeCompare(b.name));

  const L = [];
  L.push("//! The types the CRUD commands work through.");
  L.push("//!");
  L.push("//! Generated by `codegen/crud.mjs` from the schema and");
  L.push("//! `schema/get.graphql`. Do not edit; run `npm run generate`.");
  L.push("");
  L.push("/// One field of a create or edit input.");
  L.push("pub struct InputField {");
  L.push("    pub name: &'static str,");
  L.push("    /// What this is once it is JSON, for the schema `describe` prints.");
  L.push("    pub json: &'static str,");
  L.push("    pub required: bool,");
  L.push("    pub about: &'static str,");
  L.push("}");
  L.push("");
  L.push("/// A type, and the four things that can be done to it.");
  L.push("pub struct Type {");
  L.push("    /// What it is called on the command line.");
  L.push("    pub name: &'static str,");
  L.push("    pub graphql: &'static str,");
  L.push("    /// The operation in `schema/get.graphql`, and the field it returns.");
  L.push("    pub get: &'static str,");
  L.push("    pub root: &'static str,");
  L.push("    pub add: &'static str,");
  L.push("    pub update: &'static str,");
  L.push("    pub remove: &'static str,");
  L.push("    /// The GraphQL input object a create takes.");
  L.push("    pub create_input: &'static str,");
  L.push("    /// The same for an edit, where every field is optional.");
  L.push("    pub edit_input: &'static str,");
  L.push("    pub create: &'static [InputField],");
  L.push("    pub edit: &'static [InputField],");
  L.push("}");
  L.push("");
  L.push(`/// Every type with a complete set of operations. ${types.length} of them.`);
  L.push("pub const TYPES: &[Type] = &[");
  for (const t of types) {
    L.push("    Type {");
    L.push(`        name: ${rustStr(t.name)},`);
    L.push(`        graphql: ${rustStr(t.graphql)},`);
    L.push(`        get: ${rustStr(t.get)},`);
    L.push(`        root: ${rustStr(t.root)},`);
    L.push(`        add: ${rustStr(t.add)},`);
    L.push(`        update: ${rustStr(t.update)},`);
    L.push(`        remove: ${rustStr(t.remove)},`);
    L.push(`        create_input: ${rustStr(t.createInput)},`);
    L.push(`        edit_input: ${rustStr(t.editInput)},`);
    for (const [key, list] of [["create", t.create], ["edit", t.edit]]) {
      if (list.length === 0) {
        L.push(`        ${key}: &[],`);
        continue;
      }
      L.push(`        ${key}: &[`);
      for (const f of list) {
        L.push(
          `            InputField { name: ${rustStr(f.name)}, json: ${rustStr(f.json)}, ` +
            `required: ${f.required}, about: ${rustStr(f.about)} },`,
        );
      }
      L.push("        ],");
    }
    L.push("    },");
  }
  L.push("];");
  L.push("");
  return L.join("\n");
}
