// Turning the walked query into Rust.

const rustStr = (s) => JSON.stringify(s);

/** `self.opera.language.as_ref()?.name` — `?` where a link may be absent. */
function accessorChain(access) {
  let expr = "self";
  for (const link of access) {
    expr += `.${link.rust_name}`;
    if (!link.present) expr += ".as_ref()?";
  }
  return expr;
}

/** Turn the leaf at the end of a chain into `String`. */
function leafToString(expr, leaf, format) {
  if (format === "pad2") return `format!("{:02}", ${expr})`;
  return leaf === "text" ? `${expr}.clone()` : `${expr}.to_string()`;
}

function requiredArm(f) {
  // Every link is always-present, so the chain is plain field access.
  const expr = accessorChain(f.access);
  return [`${rustStr(f.path)} => ${leafToString(expr, f.leaf, f.format)},`];
}

function optionalArm(f) {
  const last = f.access[f.access.length - 1];
  const field = `${accessorChain(f.access.slice(0, -1))}.${last.rust_name}`;
  if (last.present) {
    // The leaf itself is always there; only something above it was optional,
    // and the `?` in the chain already handled that.
    return [`${rustStr(f.path)} => Some(${leafToString(field, f.leaf, f.format)}),`];
  }
  if (f.format === "pad2") {
    return [`${rustStr(f.path)} => ${field}.map(|v| format!("{v:02}")),`];
  }
  if (f.leaf === "text") return [`${rustStr(f.path)} => ${field}.clone(),`];
  return [`${rustStr(f.path)} => ${field}.map(|v| v.to_string()),`];
}

function derivedArm(d, list) {
  const src = list.present ? `self.${list.rust_name}` : `self.${list.rust_name}.as_ref()?`;
  const sel = `text(&e.${d.selectSnake})`;
  if (d.join !== undefined) {
    return [
      `${rustStr(d.path)} => {`,
      `    let vs: Vec<String> = ${src}.iter().filter_map(|e| ${sel}).collect();`,
      `    (!vs.is_empty()).then(|| vs.join(${rustStr(d.join)}))`,
      `}`,
    ];
  }
  const nth = d.index === 0 ? "first()" : `get(${d.index})`;
  return [`${rustStr(d.path)} => ${src}.${nth}.and_then(|e| ${sel}),`];
}

const indent = (lines, by) => lines.map((l) => " ".repeat(by) + l);

export function emit({ fields, structs, derived, lists, query }) {
  const L = [];
  L.push("// @generated by codegen/generate.mjs — do not edit.");
  L.push("//");
  L.push("// Regenerate with `npm run generate` in codegen/, after");
  L.push("// `npm run fetch-schema` if the API has moved on. Every field below is");
  L.push("// derived from schema/recording.graphql and schema/schema.graphql; what");
  L.push("// neither can express comes from schema/fields.mjs.");
  L.push("//");
  L.push("// A field is `non_null` when the schema marks every link above it");
  L.push("// `@semanticNonNull`. If that annotation is ever removed upstream, the");
  L.push("// change shows up here as a `String` becoming an `Option<String>`.");
  L.push("");
  L.push("use crate::model::text;");
  L.push("use crate::{FieldDoc, Fields};");
  L.push("use serde::Deserialize;");
  L.push("");
  L.push("/// The query this model deserializes, sent verbatim at runtime.");
  L.push('pub const QUERY: &str = include_str!("../../schema/recording.graphql");');
  L.push("");

  // ---- the template surface
  L.push("/// Every path a template may reference.");
  L.push("pub static FIELDS: &[FieldDoc] = &[");
  for (const f of fields) {
    const ctor = f.present ? "non_null" : "new";
    L.push(`    FieldDoc::${ctor}(${rustStr(f.path)}, ${rustStr(f.doc)}),`);
  }
  for (const d of derived) {
    L.push(`    FieldDoc::new(${rustStr(d.path)}, ${rustStr(d.doc)}),`);
  }
  L.push("];");
  L.push("");

  // ---- the deserialization types
  for (const s of structs.values()) {
    L.push("#[derive(Debug, Deserialize)]");
    L.push('#[serde(rename_all = "camelCase")]');
    L.push(`pub struct ${s.name} {`);
    for (const f of s.fields) {
      if (f.collapse) {
        // The API spells "unknown" as null, as 0, and as "" — sometimes for
        // the same field on different records. Collapsing here means the Rust
        // type says what is true, and nothing downstream has to know.
        L.push(`    #[serde(default, deserialize_with = "crate::model::de::${f.collapse}")]`);
      }
      L.push(`    pub ${f.rust_name}: ${f.rust_type},`);
    }
    L.push("}");
    L.push("");
  }

  // ---- the resolver
  const root = structs.values().next().value.name;
  L.push(`impl Fields for ${root} {`);
  L.push("    fn required(&self, path: &str) -> String {");
  L.push("        match path {");
  for (const f of fields.filter((f) => f.present)) L.push(...indent(requiredArm(f), 12));
  L.push('            other => unreachable!("{other} is not a non-null field"),');
  L.push("        }");
  L.push("    }");
  L.push("");
  L.push("    fn optional(&self, path: &str) -> Option<String> {");
  L.push("        match path {");
  for (const f of fields.filter((f) => !f.present)) L.push(...indent(optionalArm(f), 12));
  for (const d of derived) L.push(...indent(derivedArm(d, lists.get(d.from)), 12));
  L.push('            other => unreachable!("{other} is not a nullable field"),');
  L.push("        }");
  L.push("    }");
  L.push("}");
  L.push("");
  return L.join("\n");
}
